version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: flightHub
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: flightHub
      DB_USERNAME: root
      DB_PASSWORD: password
    depends_on:
      - mysql
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data:
